ansible_host: "{{ mgmt_ip | ipaddr('address') }}"
interfaces:
  - interface: Gi0/1
    description: to lab-ca-1
    ip: 70.0.0.2/30
  - interface: Gi0/3
    description: to lab-cae-2
    ip: 70.0.3.1/30
  - interface: Gi0/4
    description: to lab-pe-1
    ip: 40.0.0.2/30
  - interface: loopback0
    description: loopback
    ip: 12.12.12.2/32
