interfaces:
  - interface: Gi0/4
    description: to cae-1
    ip: 40.0.0.1/30
  - interface: Gi0/3
    description: to pe-2
    ip: 10.0.10.2/30
  - interface: Gi0/2
    ip: 10.0.13.1/30
    description: to p2
  - interface: Gi0/1
    description: to p1
    ip: 10.0.11.1/30
  - interface: loopback0
    description: loopback0
    ip: 11.11.11.1/32
