#actions to be performed by nerautomator

- hosts: netautomator-1
  gather_facts: none

  tasks:
    # - name: getting git respository
    #   git:
    #     repo: https://github.com/Krlosromero/demo-ansible-gns3.git
    #     dest: /var/tmp
    - name: Copy REPO to Netautomator
      copy:
        src: "{{ lookup('env', 'NETAUTOMATOR_REPO') }}"
        dest: /var/tmp

    - name: run script
      command: uptime
      register: result

    - debug:
        msg: System uptime {{ result }}
