---
ansible_user: "{{ lookup('env', 'NET_DEVICE_USER') }}"
ansible_password: "{{ lookup('env', 'NET_DEVICE_PASSWORD') }}"
ansible_connection: network_cli
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable
ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q root@netautomator"'
