---
- hosts: network
  gather_facts: no

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - ios_command:
        commands:
          - show version
      register: result

    - debug:
        msg: "{{ result.stdout_lines[0][0] }}"
