#### GNS3 Server settings
gns3_url: "http://dev_gns3server"
gns3_project_name: mpls_lab
gns3_lab_user: netops
gns3_lab_pass: netops123456
gns3_nodes_strategy: all

### Nodes attributes and specifications
gns3_nodes_spec:
    - name: ca-1
      template: "Cisco IOSv 15.7(3)M3"
    - name: cae-1
      template: "Cisco IOSv 15.7(3)M3"
    - name: cae-2
      template: "Cisco IOSv 15.7(3)M3"
    - name: cb-1
      template: "Cisco IOSv 15.7(3)M3"
    - name: cbe-1
      template: "Cisco IOSv 15.7(3)M3"
    - name: cbe-2
      template: "Cisco IOSv 15.7(3)M3"
    - name: pe-1
      template: "Cisco IOSv 15.7(3)M3"
    - name: pe-2
      template: "Cisco IOSv 15.7(3)M3"
    - name: pe-3
      template: "Cisco IOSv 15.7(3)M3"
    - name: pe-4
      template: "Cisco IOSv 15.7(3)M3"
    - name: p-1
      template: "Cisco IOSv 15.7(3)M3"
    - name: p-2
      template: "Cisco IOSv 15.7(3)M3"
    - name: netautomator-1
      template: "netautomator"
    - name: cloud-1
      template: "Cloud"
    - name: switch-1
      template: "Ethernet switch"
    - name: switch-2
      template: "Ethernet switch"

### Links mapping
gns3_links_spec:
    - ["ca-1", "Gi0/0", "switch-1", "Ethernet0"]
    - ["cae-1", "Gi0/0", "switch-1", "Ethernet1"]
    - ["pe-1", "Gi0/0", "switch-1", "Ethernet2"]
    - ["p-1", "Gi0/0", "switch-1", "Ethernet3"]
    - ["pe-3", "Gi0/0", "switch-1", "Ethernet4"]
    - ["cbe-1", "Gi0/0", "switch-1", "Ethernet5"]
    - ["cb-1", "Gi0/0", "switch-1", "Ethernet0"]
    - ["cae-2", "Gi0/0", "switch-1", "Ethernet1"]
    - ["pe-2", "Gi0/0", "switch-1", "Ethernet2"]
    - ["p-2", "Gi0/0", "switch-1", "Ethernet3"]
    - ["pe-4", "Gi0/0", "switch-1", "Ethernet4"]
    - ["cbe-2", "Gi0/0", "switch-1", "Ethernet5"]
    - ["switch-1", "Ethernet6", "switch-2", "Ethernet6"]
    - ["netautomator-1", "eth0", "switch-2", "Ethernet7"]
    - ["cloud-1", "eth1", "netautomator-1", "eth1"]
    - ["ca-1", "Gi0/1", "cae-1", "Gi0/1"]
    - ["ca-1", "Gi0/2", "cae-2", "Gi0/2"]
    - ["cae-1", "Gi0/3", "cae-2", "Gi0/3"]
    - ["cae-1", "Gi0/4", "pe-1", "Gi0/4"]
    - ["cae-2", "Gi0/4", "pe-2", "Gi0/4"]
    - ["pe-1", "Gi0/3", "pe-2", "Gi0/3"]
    - ["pe-1", "Gi0/1", "p-1", "Gi0/1"]
    - ["pe-2", "Gi0/2", "p-1", "Gi0/2"]
    - ["pe-2", "Gi0/1", "p-2", "Gi0/1"]
    - ["pe-1", "Gi0/2", "p-2", "Gi0/2"]
    - ["p-1", "Gi0/3", "p-2", "Gi0/3"]
    - ["p-1", "Gi0/4", "pe-4", "Gi0/4"]
    - ["p-1", "Gi0/5", "pe-3", "Gi0/5"]
    - ["p-2", "Gi0/4", "pe-3", "Gi0/4"]
    - ["p-2", "Gi0/5", "pe-4", "Gi0/5"]
    - ["pe-3", "Gi0/3", "pe-4", "Gi0/3"]
    - ["pe-3", "Gi0/2", "cbe-1", "Gi0/2"]
    - ["pe-4", "Gi0/1", "cbe-2", "Gi0/1"]
    - ["cbe-1", "Gi0/3", "cbe-2", "Gi0/3"]
    - ["cbe-1", "Gi0/1", "cb-1", "Gi0/1"]
    - ["cbe-2", "Gi0/2", "cb-1", "Gi0/2"]

### Boilerplate configuration settings
boilerplate:
    # `generate` or `deploy` the configuration
    config: "generate"
    # Flag used when config is set to `deploy`. When `no` it will prompt the user for
    # confirmation, when set to `yes` it will wait the minuites set in `automated_push_delay`
    automated_push: "yes"
    automated_push_delay: 2

